<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>html</string>
		<string>htm</string>
		<string>shtml</string>
		<string>xhtml</string>
		<string>phtml</string>
		<string>inc</string>
		<string>tmpl</string>
		<string>tpl</string>
		<string>ctp</string>
	</array>
	<key>firstLineMatch</key>
	<string>{%(?i:html)</string>
	<key>keyEquivalent</key>
	<string>^~H</string>
	<key>name</key>
	<string>FIS (tpl)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#script</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#tag</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#blocks</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>blocks</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\{%?)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.smarty.fis</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(%?\})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.smarty.fis</string>
						</dict>
					</dict>
					<key>name</key>
					<string>source.smarty.fis</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#strings</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#variables</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#lang</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\{%?)\*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.smarty.fis</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*(%?\})</string>
					<key>name</key>
					<string>comment.block.smarty.fis</string>
					<key>patterns</key>
					<array>
					</array>
				</dict>
			</array>
		</dict>
		<key>lang</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(!=|!|&lt;=|&gt;=|&lt;|&gt;|===|==|%|&amp;&amp;|\|\|)|\b(and|or|eq|neq|ne|gte|gt|ge|lte|lt|le|not|mod)\b</string>
					<key>name</key>
					<string>keyword.operator.smarty.fis</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(TRUE|FALSE|true|false)\b</string>
					<key>name</key>
					<string>constant.language.smarty.fis</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(if|else|elseif|foreach|foreachelse|section|switch|case|break|default)\b</string>
					<key>name</key>
					<string>keyword.control.smarty.fis</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.smarty.fis</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b([a-zA-Z]+)=</string>
					<key>name</key>
					<string>meta.attribute.smarty.fis</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(capture|config_load|counter|cycle|debug|eval|fetch|include_php|include|insert|literal|math|strip|rdelim|ldelim|assign|constant|block|html_[a-z_]*)\b</string>
					<key>name</key>
					<string>support.function.built-in.smarty.fis</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(require|block|widget|script|extend)\b</string>
					<key>name</key>
					<string>support.function.built-in.smarty.fis</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\|(capitalize|cat|count_characters|count_paragraphs|count_sentences|count_words|date_format|default|escape|indent|lower|nl2br|regex_replace|replace|spacify|string_format|strip_tags|strip|truncate|upper|wordwrap)</string>
					<key>name</key>
					<string>support.function.variable-modifier.smarty.fis</string>
				</dict>
			</array>
		</dict>
		<key>script</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?:^\s+)?({%)((?i:script))\b(?![^%}]*/%})</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.function.built-in.smarty.fis</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?&lt;={%/(script))(%})(?:\s*\n)?</string>
					<key>endCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>source.js.embedded.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-stuff</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;!{%/(?:script))(%})</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.html</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>support.function.built-in.smarty.fis</string>
								</dict>
							</dict>
							<key>end</key>
							<string>({%/)((?i:script))</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.comment.js</string>
										</dict>
									</dict>
									<key>match</key>
									<string>(//).*?((?={%/script)|$\n?)</string>
									<key>name</key>
									<string>comment.line.double-slash.js</string>
								</dict>
								<dict>
									<key>begin</key>
									<string>/\*</string>
									<key>captures</key>
									<dict>
										<key>0</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.comment.js</string>
										</dict>
									</dict>
									<key>end</key>
									<string>\*/|(?={%/script)</string>
									<key>name</key>
									<string>comment.block.js</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#php</string>
								</dict>
								<dict>
									<key>include</key>
									<string>source.js</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.smarty.fis</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.smarty.fis</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.smarty.fis</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.smarty.fis</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.smarty.fis</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.smarty.fis</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.smarty.fis</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.smarty.fis</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>tag</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>({%/?)((?i:body|head|html)\b)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.function.built-in.smarty.fis</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(%})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.tag.structure.any.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-stuff</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>variables</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.smarty.fis</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(\$)Smarty\.</string>
					<key>name</key>
					<string>variable.other.global.smarty.fis</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.smarty.fis</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.smarty.fis</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\$)([a-zA-Z_][a-zA-Z0-9_]*)\b</string>
					<key>name</key>
					<string>variable.other.smarty.fis</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.smarty.fis</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.property.smarty.fis</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(-&gt;)([a-zA-Z_][a-zA-Z0-9_]*)\b</string>
					<key>name</key>
					<string>variable.other.smarty.fis</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.smarty.fis</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.function-call.object.smarty.fis</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.smarty.fis</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.smarty.fis</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(-&gt;)([a-zA-Z_][a-zA-Z0-9_]*)(\().*?(\))</string>
					<key>name</key>
					<string>variable.other.smarty.fis</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.fis</string>
	<key>uuid</key>
	<string>CC844414-2CEB-C81D-06D3-E7AC174FF2DE</string>
</dict>
</plist>
